import { StyleSheet, Dimensions } from "react-native";
const ScreenWidth = Dimensions.get('window').width;

export const styles = StyleSheet.create({
  btn: {
    width: 90,
    height: 45,
    backgroundColor: '#453D98ff',
    borderRadius: 10,
    elevation: 4,
    justifyContent: 'center',
  },
  btntext: {
    alignSelf: 'center',
    color: 'white',
    fontWeight: 'bold',
    fontSize: 18,
  },
  dropdown: {
    height: 50,
    width: ScreenWidth * 0.75,
    borderColor: 'black',
    borderRadius: 8,
    paddingHorizontal: 8,
    alignSelf: 'center',
    backgroundColor: '#e6eff0',
    paddingHorizontal: 15,
  },
  placeholderStyle: {
    fontSize: 15,
    color: '#6c6f73',
  },
  selectedTextStyle: {
    fontSize: 15,
    color: '#6c6f73',
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 15,
    color: '#6c6f73',
  },
  container: {
    alignItems: 'center',
    flexDirection: 'column',
    paddingHorizontal: 20,
    width: ScreenWidth,
  },
  levelContainer: {
    backgroundColor: '#fcfafb',
    width: '100%',
    margin: 10,
    borderRadius: 15,
    borderWidth: 0.5,
    borderColor: 'gray',
  },
  levelText: {
    alignItems: 'flex-start',
    padding: 5,
    marginLeft: '5%',
    color: 'black',
    fontSize: 13,
    fontFamily: 'PoppinsMedium',
  },
  MandatoryText: {
    alignItems: 'flex-start',
    padding: 5,
    marginLeft: '5%',
    color: 'black',
    fontSize: 10,
    fontFamily: 'PoppinsRegular',
  },
  Uploadimg: {
    height: 30,
    width: 30,
    position: 'absolute',
    right: 0,
    bottom: 0,
  },
  inputContainer: {
    height: 50,
    width: ScreenWidth * 0.8,
    backgroundColor: '#e6eff0',
    flexDirection: 'row',
    paddingHorizontal: 15,
    borderRadius: 10,
    alignItems: 'center',
    borderColor: 'black',
    alignSelf: 'center',
  },
  inputContainerforbtn: {
    height: 50,
    width: '83%',
    backgroundColor: '#e6eff0',
    flexDirection: 'row',
    paddingHorizontal: 15,
    borderRadius: 10,
    alignItems: 'center',
    borderColor: 'black',
    alignSelf: 'center',
  },
  inputContainerend: {
    height: 50,
    width: '90%',
    backgroundColor: '#e6eff0',
    flexDirection: 'row',
    paddingHorizontal: 15,
    borderRadius: 10,
    alignItems: 'center',
    borderColor: 'black',
    alignSelf: 'center',
    marginBottom: 10,
  },
  rightIcon: {
    height: 30,
    width: 30,
  },
  rightIconFile: {
    height: 30,
    width: 30,
    margin: '15%',
  },
  dropdownend: {
    height: 50,
    width: '90%',
    borderColor: 'black',
    borderRadius: 8,
    alignSelf: 'center',
    backgroundColor: '#e6eff0',
    paddingHorizontal: 15,
    marginBottom: 10,
  },
});
