import { StyleSheet } from "react-native";
import { darkBlue } from "../components/constant";
export const styles = StyleSheet.create({
    maincontainer: {
      flex: 1,
    },
    container: {
      flex: 1,
      padding: 16,
    },
    header: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 16,
      color: 'black',
    },
    box: {
      borderWidth: 1,
      borderColor: 'black',
      padding: 16,
      marginBottom: 16,
    },
    boxHeader: {
      fontSize: 18,
      marginBottom: 8,
      color: darkBlue,
      textAlign: 'center',
      fontFamily: 'PoppinsBold',
      letterSpacing: 0.5,
    },
    fieldContainer: {
      marginBottom: 16,
    },
    label: {
      fontSize: 16,
      marginBottom: 8,
      color: 'black',
    },
    input: {
      paddingTop: 13,
      paddingLeft: 30,
      letterSpacing: 0.5,
      color: 'black',
      fontSize: 15,
      width: '80%',
      fontFamily: 'PoppinsSemiBold',
    },
    dropdown:{
      width: '80%',
      borderRadius: 10,
      height: 50,
      borderWidth: 1,
      borderColor: '#453D98',
      marginTop: 10,color:'black',paddingHorizontal:10,
      color:'black'
    },
    resizableInput: {
      borderColor: 'black',
      borderWidth: 1,
      borderRadius: 4,
      padding: 8,
      color: 'black',
      height: 100,
    },
    submitButton: {
      backgroundColor: darkBlue,
      borderRadius: 5,
      marginTop: 30,
      marginBottom: 20,
      height: 50,
      width:'48%',
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    buttonText: {
      color: 'white',
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 18,
    },
    modalContainer: {
      flex: 1,
      padding: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalHeaderText: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 16,
      marginTop: 8,
      color: darkBlue,
      textAlign: 'center',
      fontFamily: 'PoppinsBold',
    },
    modalScrollView: {
      flex: 1,
      width: '100%',
    },
    modalField: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    modalFieldLabel: {
      fontSize: 18,
      fontWeight: 'bold',
      color: 'black',
    },
    modalFieldValue: {
      fontSize: 18,
      color: 'black',
    },
    closeButton: {
      backgroundColor: darkBlue,
      borderRadius: 5,
      marginTop: 10,
      marginBottom: 20,
      height: 50,
      width: 150,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    MandatoryText: {
      alignItems: 'flex-start',
      marginBottom: 10,
      color: 'black',
      fontSize: 10,
      fontFamily: 'PoppinsRegular',
    },
    inputContainer: {
      height: 55,
      width: 300,
      backgroundColor: '#9894e6',
      // backgroundColor:"black",
      flexDirection: 'row',
      paddingHorizontal: 15,
      borderRadius: 10,
      // borderWidth: 0.5,
      alignItems: 'center',
      marginTop: 30,
    },
    leftIcon: {
      position: 'absolute',
      left: 0,
      height: 25,
      width: 25,
      margin: 10,
      tintColor: 'black',
    },
    container: {
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: '30%',
      marginBottom: 20,
    },
    leftIcon: {
      position: 'absolute',
      left: 0,
      height: 25,
      width: 25,
      margin: 10,
      tintColor: 'black',
    },
    image: {
      height: 200,
      width: '100%',
      backgroundColor: darkBlue,
      borderRadius: 10,
    },
    inputContainer: {
      height: 55,
      width: 300,
      backgroundColor: '#9894e6',
      // backgroundColor:"black",
      flexDirection: 'row',
      paddingHorizontal: 15,
      borderRadius: 10,
      // borderWidth: 0.5,
      alignItems: 'center',
      marginTop: 30,
    },
    input: {
      paddingTop: 13,
      paddingLeft: 30,
      letterSpacing: 0.5,
      color: 'black',
      fontSize: 15,
      width: 250,
      fontFamily: 'PoppinsSemiBold',
    },
    leftIcon: {
      position: 'absolute',
      left: 0,
      height: 25,
      width: 25,
      margin: 10,
      tintColor: 'black',
    },
    button: {
      backgroundColor: darkBlue,
      borderRadius: 5,
      marginTop: 30,
      marginBottom: 20,
      height: 50,
      width: 300,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    buttonText: {
      color: 'white',
      textAlign: 'center',
      // fontWeight: 'bold',
      fontSize: 16,
      letterSpacing: 0.5,
      fontFamily: 'PoppinsSemiBold',
    },
    linkText: {
      color: darkBlue,
      fontSize: 16,
      fontWeight: '500',
    },
    loadingContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    registerTextContainer: {
      flexDirection: 'column',
      alignItems: 'center',
    },
    blackText: {
      color: 'black',
      fontSize: 14,
      fontFamily: 'PoppinsMedium',
    },
    blueText: {
      color: darkBlue,
      fontSize: 14,
      // fontWeight: '500',
      fontFamily: 'PoppinsBold',
    },
    toastContainer: {
      borderRadius: 5,
      position: 'absolute',
      bottom: '9%', // Center vertically
      left: '26%', // Center horizontally
      transform: [{translateX: -50}, {translateY: -50}], // Center both horizontally and vertically
    },
    toastText: {
      color: 'red',
      fontSize: 10,
      textAlign: 'center',
      fontFamily: 'PoppinsMedium',
      shadowColor: 'black', // Set shadow color to blue
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.5,
      shadowRadius: 3,
      elevation: 10, // This is for Android
    },
  });